#!/bin/sh -e

LOG=/mnt/log/setup.log

cd /mnt/log

touch thin.log "$LOG"
chown redmine:nobody *

cd /srv/redmine

[ ! -f "/mnt/_/configuration.yml" ] || {
    cp -f /mnt/_/configuration.yml config/
    chown redmine:nobody config/configuration.yml
    chmod 0644 config/configuration.yml
}

[ -f "config/initializers/secret_token.rb" ] \
 || su - redmine -c "bundle exec rake generate_secret_token >> $LOG 2>&1"

[ -f "/mnt/redmine/.migrated" ] || {
    touch /mnt/redmine/.migrated
    su - redmine -c "RAILS_ENV=production bundle exec rake db:migrate >> $LOG 2>&1"
    su - redmine -c "RAILS_ENV=production REDMINE_LANG=en bundle exec rake redmine:load_default_data >> $LOG 2>&1"
    su - redmine -c "RAILS_ENV=production bundle exec rake redmine:plugins:migrate >> $LOG 2>&1"
}
