#!/bin/sh -e

sed -i -e "/GIT_CONFIG_KEYS/s/''/'.*'/" \
    -e '/# LOCAL_CODE                =>  "$ENV{HOME}\/local"/s/#/ /' \
    /mnt/git/.gitolite.rc

cp -f /root/.ssh/id_rsa /srv/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa
cp -f /root/.ssh/id_rsa.pub /srv/redmine/plugins/redmine_git_hosting/ssh_keys/redmine_gitolite_admin_id_rsa.pub
chown redmine:nobody /srv/redmine/plugins/redmine_git_hosting/ssh_keys/*
