---
chdir: "/srv/redmine"
environment: production
address: 0.0.0.0
port: 3000
timeout: 30
log: "/mnt/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 65535
max_persistent_conns: 512
require: []
wait: 30
threadpool_size: 20
user: redmine
daemonize: false
